# Generated by Django 4.0.5 on 2024-10-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('Report_id', models.AutoField(primary_key=True, serialize=False)),
                ('Staff_id', models.IntegerField(max_length=7)),
                ('Student_id', models.CharField(max_length=12)),
            ],
        ),
    ]
